### ISSUE TITLE
venv paths incorrect on windows

### ISSUE THREAD

**Issue by ciarancourtney** [David-OConnor/pyflow#17]
![image](https://user-images.githubusercontent.com/6096029/66273293-7ba37c80-e86a-11e9-9dd9-647f1ed9686e.png)

Standard Windows venv seems to be set up in `.venv`, but then packages seem to be installed in `lib/`, as if it detects a non-windows environment.

Could pyflow adopt Linux style venv paths on windows i.e. `bin/` instead of `Scripts/`, `lib` instead of `Lib` etc. Not sure what the history for this difference is on windows.

**Comment by David-OConnor** [comment]
This is intentional - `lib` is where packages are installed per [PEP 582](https://www.python.org/dev/peps/pep-0582/). The venv is meant to operate behind-the-scenes, as a safety layer against modifying a Py install directly. I don't think it's feasible to modify `Scripts` and `Lib` without changing the behavior of Python's `venv`.

**Comment by David-OConnor** [comment]
Closing, since there doesn't seem to be a nice way around this. I agree that it would be nice if python would use the same folder structure on Windows as it does on linux and Mac.
