### ISSUE TITLE
Suggestion: Publish prebuilt wheels on PyPI

### ISSUE THREAD

**Issue by frostming** [David-OConnor/pyflow#22]
It would be great if users can install pyflow with `pip`. It can be done by publishing a prebuilt binary wheel on PyPI for every OS arch. I am not familiar with this task but `setuptools-rust` may be helpful.

**Comment by David-OConnor** [comment]
I didn't realize this was possible, but would be a nice addition - looking into it now. (Also WIP on getting this on `snap`, but need classic confinement)

**Comment by David-OConnor** [comment]
A Windows wheel is now available via `pip install pflow`. Built using [maturin](https://github.com/PyO3/maturin), which is a cfg-free variant of `setuptools-rust`.

Currently unable to built a proper linux wheel due to issues with OpenSSL linking (ie `auditwheel` is failing the wheel due to not meeting the `manylinux` spec) - which may indicate a broader linux compatibility problem. For example, Redhat family OSes won't work with the standalone linux binary due to OpenSSL compatibility.

I suspect this is solvable by vendorizing `openSSl`, but am not sure how to do this currently.

**Comment by David-OConnor** [comment]
Figured out how to vendorize `openSSl` by modifying the features of the `reqwest` dependency; now need to find out how to do the same for `liblzma`

**Comment by David-OConnor** [comment]
Now works for Win and Linux.
