### ISSUE TITLE
Considering a breaking pivot

### ISSUE THREAD

**Issue by David-OConnor** [David-OConnor/pyflow#87]
2 Points

1: I've been neglecting this repo due to being in over my head on other projects. Sorry!

2: I'm leaning towards dropping support for all Python versions except for the most recent. This will simplify things a bit, but more importantly, I think this aligns better with my thoughts on the future of Python in general. I don't like the idea of encouraging older versions to perpetuate (especially if newer ones are backwards compatible), and leaving the ecosystem a mix of many diff versions. 

Thoughts? If you're using 3.6, 3.7 etc, why? Would switching to 3.8 break anything for you?

**Comment by 99hats** [comment]
Personally, my interest in pyflow is it's ability to manage packages _and_ python version (maybe this is not what you mean). Otherwise, I'm not sure why choose pyflow. That said, I appreciate the work you've put in so far.

Also, PySide2 currently has issues with 3.8, so it would break what I'm doing currently.

**Comment by David-OConnor** [comment]
Thanks. After more consideration including your comment, I'm now leaning away from this. A number of packages don't work with newer Py versions.
